spring.application.name=aydin-banka-sistemi
spring.datasource.url=jdbc:h2:file:./data/bankadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=h.spring.field.990@gmail.com
spring.mail.password=SpringFramework111
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
